# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: build GitHub Pages site

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: "docs/**"

  # Runs on pushes targeting the default branch
  #  push:
  #    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out files
        uses: actions/checkout@v4

      - name: set up GitHub Pages configuration
        uses: actions/configure-pages@v4

      - name: build site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: upload site
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy site
        id: deployment
        uses: actions/deploy-pages@v4
