name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  builds:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - elixir-version: "1.9.4-otp-22"
            otp-version: "22.3.4.26"
          - elixir-version: "1.10.4-otp-22"
            otp-version: "22.3.4.26"
          - elixir-version: "1.10.4-otp-23"
            otp-version: "23.3.4.18"
          - elixir-version: "1.11.4-otp-22"
            otp-version: "22.3.4.26"
          - elixir-version: "1.11.4-otp-23"
            otp-version: "23.3.4.18"
          - elixir-version: "1.11.4-otp-24"
            otp-version: "24.3.4.11"
          - elixir-version: "1.12.3-otp-22"
            otp-version: "22.3.4.26"
          - elixir-version: "1.12.3-otp-23"
            otp-version: "23.3.4.18"
          - elixir-version: "1.12.3-otp-24"
            otp-version: "24.3.4.11"
          - elixir-version: "1.13.4-otp-22"
            otp-version: "22.3.4.26"
          - elixir-version: "1.13.4-otp-23"
            otp-version: "23.3.4.18"
          - elixir-version: "1.13.4-otp-24"
            otp-version: "24.3.4.11"
          - elixir-version: "1.13.4-otp-25"
            otp-version: "25.3.2"
          - elixir-version: "1.14.4-otp-23"
            otp-version: "23.3.4.18"
          - elixir-version: "1.14.4-otp-24"
            otp-version: "24.3.4.11"
          - elixir-version: "1.14.4-otp-25"
            otp-version: "25.3.2"
    steps:
      - name: check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: install elixir and erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
          version-type: strict

      - name: install hex and rebar3
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: install dependencies
        run: |
          mix deps.get

      - name: compile code
        run: |
          mix compile

      # should be a separate job so it generates a separate check
      - name: lint code
        run: |
          mix credo

      # should be a separate job so it generates a separate check
      - name: typecheck
        run: |
          mix dialyzer
