name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to release.
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: publish to hex.pm
        uses: HypeRate/action-publish-hex@v2
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
